### ISSUE TITLE
There is no way to disable ssl certificate check

### ISSUE THREAD

**Issue by Yrok472** [v1k45/python-qBittorrent#37]
I'm using https + Let's encrypt.  But sometimes need to test something with self-signed certs. I got

`>>>qb = Client('htts://<my-domain>:8080/')
Traceback (most recent call last):
  File "/home/tg/.local/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 485, in wrap_socket
    cnx.do_handshake()
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1808, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1548, in _raise_ssl_error
    _raise_current_error()
  File "/usr/lib/python3/dist-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]`

Currently need to patch client.py (add `verify=False` in requests call). IMHO will be nice to have an option, where user can disable ssl verification.

**Comment by v1k45** [comment]
Sounds like a good feature. A PR is welcome, if you'd like to contribute.

Otherwise I can take a look in few days.

**Comment by v1k45** [comment]
@Yrok472 I've created a PR for this, would you like to test it?

**Comment by Yrok472** [comment]
Thank you, i'll try tomorrow.

**Comment by Yrok472** [comment]
@v1k45 , fix works, thank you again! IMHO you can merge it.

**Comment by v1k45** [comment]
The fix is now available from 0.4.2. https://pypi.org/project/python-qbittorrent/0.4.2/
