### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x81 in position 18301: invalid start byte

### ISSUE THREAD

**Issue by 11philip22** [v1k45/python-qBittorrent#39]
i get this error when i try to load a torrent from file
```python
qbittorrent = Client('http://myip:8080/')
qbittorrent.login('admin', 'my password')
with open(torrent_file, "r") as file:
    qbittorrent.download_from_file(file_buffer=file, save_path=location)
```
```
Traceback (most recent call last):
  File "deluxe/make_torrent.py", line 66, in <module>
    qbittorrent.download_from_file(file_buffer=file, save_path=location)
  File "/usr/lib/python3.8/site-packages/qbittorrent/client.py", line 384, in download_from_file
    return self._post('torrents/add', data=data, files=torrent_files)
  File "/usr/lib/python3.8/site-packages/qbittorrent/client.py", line 64, in _post
    return self._request(endpoint, 'post', data, **kwargs)
  File "/usr/lib/python3.8/site-packages/qbittorrent/client.py", line 86, in _request
    request = self.session.post(final_url, data, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 452, in prepare_request
    p.prepare(
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 316, in prepare
    self.prepare_body(data, files, json)
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 504, in prepare_body
    (body, content_type) = self._encode_files(files, data)
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 159, in _encode_files
    fdata = fp.read()
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x81 in position 18301: invalid start byte
```

**Comment by v1k45** [comment]
@11philip22 Sorry for the late reply, torrent files contain binary data, you have to open it in `rb` mode.

Let me know if this works for you:

```python
qbittorrent = Client('http://myip:8080/')
qbittorrent.login('admin', 'my password')
with open(torrent_file, "rb") as file:
    qbittorrent.download_from_file(file_buffer=file, save_path=location)
```

**Comment by 11philip22** [comment]
Yes that works. Thanks!
