### ISSUE TITLE
ValueError when attempting download_from_file

### ISSUE THREAD

**Issue by jerblack** [v1k45/python-qBittorrent#5]
Can you please help understand what I am doing wrong here? I am just trying to add a torrent from a torrent file to qbittorrent v3.3.3.

``` python
tor = r"\\server\d\Downloads\AddTorrentComic\sample1.torrent"
f = open(tor)
o.qb.download_from_file(f, label='comics')
```

This gives me the following error:

``` python
Traceback (most recent call last):
  File "C:\Torrents\utilities\qbittorrent_port_updater.py", line 111, in <module>
    start()
  File "C:\Torrents\utilities\qbittorrent_port_updater.py", line 39, in start
    nt.check(o)
  File "C:\Torrents\utilities\qbittorrent_port_updater.py", line 94, in check
    o.qb.download_from_file(f, label='comics')
  File "C:\Python27\lib\site-packages\qbittorrent\client.py", line 321, in download_from_file
    return self._post('command/upload', data=data, files=torrent_files)
  File "C:\Python27\lib\site-packages\qbittorrent\client.py", line 46, in _post
    return self._request(endpoint, 'post', data, **kwargs)
  File "C:\Python27\lib\site-packages\qbittorrent\client.py", line 68, in _request
    request = rq.post(final_url, data, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 511, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 454, in request
    prep = self.prepare_request(req)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 388, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Python27\lib\site-packages\requests\models.py", line 296, in prepare
    self.prepare_body(data, files, json)
  File "C:\Python27\lib\site-packages\requests\models.py", line 447, in prepare_body
    (body, content_type) = self._encode_files(files, data)
  File "C:\Python27\lib\site-packages\requests\models.py", line 132, in _encode_files
    for (k, v) in files:
ValueError: need more than 1 value to unpack
```

**Comment by v1k45** [comment]
Thanks for reporting :+1: , will update PyPI package ASAP!

This happened because the download methods were refactored in in a PR, one more reason to write test!
